import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css';
import dynamic from "next/dynamic";
import NavigationBar from "@/components/global/navigation-bar";
import Header from "@/components/global/header";
import APIHandler from "@/components/APIHandler";
import { ReactNode } from "react";
import LoginedStyleWrapper from "@/components/Auth/LoginedStyleWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AJ Student Portal",
  description: "Generated by Next js.",
};

const DependencyWrapper = dynamic(()=> import("@/components/DependencyWrapper"),{ssr:false})
export default function RootLayout(props: Readonly<{
  children: ReactNode;
  transactions: ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={inter.className}>
      <DependencyWrapper>
      <NavigationBar/>
      <Header/>
      <APIHandler/>
      <main className="">
        <LoginedStyleWrapper>
    {props.children}
        </LoginedStyleWrapper>
      </main>
      </DependencyWrapper>
      </body>
    </html>
  );
}
